"""Guardrails deterministas del agente.

Esta es la frontera pública para decisiones de conversación y validación de
salidas. El resto de la aplicación no debe inventar reglas paralelas.
"""

from app.guardrails.conversation import (
    dedupe_artifacts,
    grounding_violation,
    handoff_policy,
    is_courtesy_text,
    is_payment_reason,
    is_simple_greeting,
    is_small_talk,
    latest_user_text,
    should_discard_handoff,
)
from app.guardrails.response import (
    GuardrailResult,
    HANDOFF_RULES,
    OFFICIAL_CONTACTS,
    SAFE_FALLBACK,
    SAFE_TECHNICAL_FALLBACK,
    Violation,
    check_reply,
    guard_reply,
    image_urls_on_own_line,
    no_cash_on_delivery,
    no_duplicates_within_reply,
    no_internal_context,
    no_repeated_products,
    no_system_prompt_leak,
    no_third_party_contact,
    prices_are_sourced,
    sanitize_reply,
)
from app.guardrails.input import (
    InputGuardResult,
    InjectionFinding,
    SAFE_INJECTION_REPLY,
    UNTRUSTED_CONTENT_REMOVED,
    detect_prompt_injection,
    sanitize_messages_for_model,
    sanitize_tool_result,
    sanitize_untrusted_text,
)
from app.guardrails.parameters import (
    MCP_ARGUMENT_SCHEMAS,
    ParameterValidation,
    ParameterValidationError,
    validate_arguments,
    validate_mcp_arguments,
)
from app.guardrails.privacy import (
    PrivacyResult,
    find_contacts,
    minimize_historical_messages,
    protect_json_for_model,
    protect_profile,
    redact_personal_data,
)

__all__ = [
    "GuardrailResult",
    "HANDOFF_RULES",
    "OFFICIAL_CONTACTS",
    "InputGuardResult",
    "InjectionFinding",
    "MCP_ARGUMENT_SCHEMAS",
    "ParameterValidation",
    "ParameterValidationError",
    "PrivacyResult",
    "SAFE_FALLBACK",
    "SAFE_INJECTION_REPLY",
    "SAFE_TECHNICAL_FALLBACK",
    "UNTRUSTED_CONTENT_REMOVED",
    "Violation",
    "check_reply",
    "dedupe_artifacts",
    "find_contacts",
    "detect_prompt_injection",
    "grounding_violation",
    "guard_reply",
    "handoff_policy",
    "image_urls_on_own_line",
    "is_courtesy_text",
    "is_payment_reason",
    "is_simple_greeting",
    "is_small_talk",
    "latest_user_text",
    "minimize_historical_messages",
    "no_cash_on_delivery",
    "no_duplicates_within_reply",
    "no_internal_context",
    "no_repeated_products",
    "no_system_prompt_leak",
    "no_third_party_contact",
    "prices_are_sourced",
    "protect_json_for_model",
    "protect_profile",
    "redact_personal_data",
    "sanitize_reply",
    "sanitize_messages_for_model",
    "sanitize_tool_result",
    "sanitize_untrusted_text",
    "should_discard_handoff",
    "validate_arguments",
    "validate_mcp_arguments",
]
